spring:
  datasource:
    url: jdbc:mysql://localhost:3306/expense_db?useSSL=false&serverTimezone=UTC
    username: expense_user
    password: moh107844
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

